name: pts_2023_001
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.5

dev_dependencies:
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  google_sign_in: ^6.0.2
  pinput: ^2.2.31
  step_progress_indicator: ^1.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/dll/
